# Generated by Django 6.0.2 on 2026-03-05 16:16

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biosphere", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageNodes",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("link", models.URLField(default="Link")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Citations",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="Title", max_length=255)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "authors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biosphere.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchPaper",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="Title", max_length=255)),
                ("link", models.URLField(default="Link", max_length=255)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("distribution", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="research_papers", to="biosphere.author"
                    ),
                ),
                (
                    "cites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cited_by",
                        to="search_database.researchpaper",
                    ),
                ),
                ("images", models.ManyToManyField(to="search_database.imagenodes")),
            ],
        ),
        migrations.CreateModel(
            name="DocumentChunks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="Number of chunk in the paper"),
                ),
                (
                    "section_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("text_content", models.TextField(default="")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="search_database.researchpaper",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="research_paper_vectors_index",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
