# Generated by Django 5.2.7 on 2025-11-13 04:58

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        VectorExtension(),
    ]
