# Generated by Django 6.0.2 on 2026-03-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citations",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="imagenodes",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
