# Generated by Django 5.2.7 on 2025-11-13 09:16

from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("search_database", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractInfo",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("data", models.JSONField()),
            ],
        ),
        VectorExtension(),
    ]
