# Generated by Django 6.0.2 on 2026-03-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_database', '0002_alter_citations_id_alter_imagenodes_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citations',
            old_name='title',
            new_name='raw_text',
        ),
        migrations.RemoveField(
            model_name='citations',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='citations',
            name='link',
        ),
        migrations.AddField(
            model_name='citations',
            name='citation_context',
            field=models.TextField(blank=True, help_text='The sentence in the source paper where this was cited', null=True),
        ),
        migrations.AddField(
            model_name='citations',
            name='cited_authors',
            field=models.TextField(blank=True, help_text='Comma seperated values of authors', null=True),
        ),
        migrations.AddField(
            model_name='citations',
            name='doi',
            field=models.CharField(blank=True, help_text='e.g., 10.1038/s41526-024-00419-y', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citations',
            name='journal_name',
            field=models.CharField(blank=True, help_text="e.g., 'npj Microgravity', 'Nature'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citations',
            name='pmcid',
            field=models.CharField(blank=True, help_text='PubMed Central ID (e.g., PMC11271499)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citations',
            name='pmid',
            field=models.CharField(blank=True, help_text='PubMed ID (e.g., 39030182)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citations',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
