# Generated by Django 5.2.7 on 2025-11-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_database', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
