# Generated by Django 6.0.2 on 2026-03-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0003_rename_title_citations_raw_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchpaper",
            name="description",
        ),
        migrations.AddField(
            model_name="citations",
            name="paper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="search_database.researchpaper",
            ),
        ),
    ]
