# Generated by Django 6.0.2 on 2026-03-07 20:45

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0004_remove_researchpaper_description_citations_paper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunks",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
