# Generated by Django 6.0.2 on 2026-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0005_alter_documentchunks_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagenodes",
            name="pmcid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
