# Generated by Django 6.0.2 on 2026-03-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0006_imagenodes_pmcid"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagenodes",
            name="image_field",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
