# Generated by Django 6.0.2 on 2026-03-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0007_imagenodes_image_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagenodes",
            old_name="image_field",
            new_name="image_file",
        ),
    ]
