# Generated by Django 6.0.2 on 2026-03-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0008_rename_image_field_imagenodes_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenodes",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
