# Generated by Django 6.0.2 on 2026-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_database", "0009_alter_imagenodes_image_file"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Author",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("name", models.CharField(default="Name", max_length=255)),
                    ],
                    options={
                        "db_table": "biosphere_author",
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="authors",
            field=models.ManyToManyField(
                related_name="research_papers", to="search_database.author"
            ),
        ),
    ]
