# Generated by Django 6.0.2 on 2026-03-15 11:01

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_database', '0010_author_alter_researchpaper_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunks',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
