"""
Django settings for NASA2 project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from datetime import timedelta
from pathlib import Path
from neomodel import config  # For Neo4j setup
import logging
import os
from dotenv import load_dotenv

load_dotenv()

logging.getLogger("django.db.backends").setLevel(logging.WARNING)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-secure-8x)2$5(i@sh-4(^k0v7d*t4!7e4(!sf%+lv2-c-2vzd0)k5@jd"
)

DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "graph_database",
    "search_database",
    "biosphere",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "djoser",
    "storages",
]

# NOTE: Neo4j Configuration (independent from DATABASES)

NEOMODEL_NEO4J_BOLT_URL = os.getenv(
    "NEOMODEL_NEO4J_BOLT_URL", "bolt://neo4j:passw0rd@localhost:7687"
)
config.DATABASE_URL = NEOMODEL_NEO4J_BOLT_URL
config.SOFT_INVERSE_CARDINALITY_CHECK = True
config.MAX_POOL_SIZE = 50
config.CONNECTION_TIMEOUT = 30
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "POST",
    "PUT",
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "NASA2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

WSGI_APPLICATION = "NASA2.wsgi.application"

# Multiple Databases Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "OPTIONS": {
            "pool": {
                "min_size": 2,
                "max_size": 10,
                "timeout": 30,
            },
        },
        "NAME": os.getenv("POSTGRES_DB", "biosphere"),
        "USER": os.getenv("POSTGRES_USER", "users"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "password"),
        "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "biosphere.User"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"

DJANGO_PG_JSONSCHEMA = {"PG_COMMIT_JSONSCHEMA": True}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# NOTE: Also check this --- Logging for database queries (optional, for debugging)
# settings.py

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} - {message}",
            "style": "{",
        },
        "colored": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(log_color)s%(levelname)s%(reset)s %(asctime)s %(module)s - %(message)s",
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "bold_red",
            },
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "biosphere": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/biosphere_errors.log",
            "formatter": "verbose",
            "level": "WARNING",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
        },
        "graph_database": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/graph_database_errors.log",
            "formatter": "verbose",
            "level": "WARNING",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
        },
        "search_database": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/search_database_errors.log",
            "formatter": "verbose",
            "level": "WARNING",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
        },
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "biosphere": {
            "handlers": ["console", "biosphere"],
            "level": "INFO",
            "propagate": False,
        },
        "search_database": {
            "handlers": ["console", "search_database"],
            "level": "INFO",
            "propagate": False,
        },
        "graph_database": {
            "handlers": ["console", "graph_database"],
            "level": "INFO",
            "propagate": False,
        },
        "psycopg.pool": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "redis": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "neo4j": {
            "handlers": ["console", "graph_database"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# INFO:
# ==========================================================================
# Redis configuration
# ==========================================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True,
            },
        },
    }
}


# INFO:
# ==========================================================================
# S3 bucket configuration
# ==========================================================================

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "biosphere_admin")
AWS_SECRET_ACCESS_KEY = os.getenv(
    "AWS_SECRET_ACCESS_KEY", "biosphere_super_secret_password"
)
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "biosphere-media")

AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "http://localhost:9000")

AWS_S3_SIGNATURE_VERSION = "s3v4"

AWS_S3_FILE_OVERWRITE = False


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


DEFAULT_FILE_STORAGE = "storages.backends.s3.S3Storage"

# INFO:
# ==========================================================================
# Simple JWT + google-auth configuration
# ==========================================================================

GOOGLE_OAUTH2_CLIENT_ID = os.getenv("GOOGLE_OAUTH2_CLIENT_ID")
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH2_CLIENT_SECRET")
GOOGLE_OAUTH2_REDIRECT_URI = os.getenv("GOOGLE_OAUTH2_REDIRECT_URI")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


# INFO:
# ==========================================================================
# AI api keys
# ==========================================================================

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


# INFO:
# ==========================================================================
# LLM Retry logic
# ==========================================================================

LLM_RETRY_ATTEMPTS = 2
LLM_RETRY_MIN_WAIT = 1
LLM_RETRY_MAX_WAIT = 6
EMBEDDING_RETRY_ATTEMPTS = 3
EMBEDDING_RETRY_MIN_WAIT = 2
EMBEDDING_RETRY_MAX_WAIT = 8
