"""
Django settings for NASA2 project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from neomodel import config  # For Neo4j setup
import logging
import os

logging.getLogger("django.db.backends").setLevel(logging.WARNING)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = "django-secure-8x)2$5(i@sh-4(^k0v7d*t4!7e4(!sf%+lv2-c-2vzd0)k5@jd"

DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django_neomodel",  # For Neo4j integration
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "graph_database",
    "search_database",
    "biosphere",
    "corsheaders",
    "rest_framework",
    "django_pg_jsonschema",
]

# NOTE: Neo4j Configuration (independent from DATABASES)

NEOMODEL_NEO4J_BOLT_URL = "bolt://neo4j:passw0rd@localhost:7687"  # Fallback
config.DATABASE_URL = "bolt://neo4j:passw0rd@localhost:7687"
config.SOFT_INVERSE_CARDINALITY_CHECK = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "POST",
    "PUT",
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "NASA2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

WSGI_APPLICATION = "NASA2.wsgi.application"

# Multiple Databases Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "biosphere",
        "USER": "users",
        "PASSWORD": "password",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    },
    # TODO: Needed to create seperate schema for semantic search
    "semantic": {  # For semantic JSON storage (e.g., paper embeddings, metadata)
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "biosphere_semantic",
        "USER": "users",
        "PASSWORD": "password",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    },
}

# NOTE: Check this for further investigations Database Routers (optional, for automatic model routing)
# Add to DATABASE_ROUTERS if you have Postgres models in "abstract"
# DATABASE_ROUTERS = [
#     "biosphere.routers.AbstractRouter",
# ]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "biosphere.User"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"

DJANGO_PG_JSONSCHEMA = {"PG_COMMIT_JSONSCHEMA": True}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# NOTE: Also check this --- Logging for database queries (optional, for debugging)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.db.backends": {
            "level": "DEBUG" if DEBUG else "INFO",
            "handlers": ["console"],
        },
        "neomodel": {
            "level": "DEBUG" if DEBUG else "INFO",
            "handlers": ["console"],
        },
    },
}
