# Generated by Django 5.2.7 on 2025-11-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Researcher', 'Researcher'), ('Explorer', 'Explorer')], default='Explorer')),
            ],
        ),
    ]
