# Generated by Django 6.0.2 on 2026-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biosphere", "0001_initial"),
        ("search_database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="papers",
            field=models.ManyToManyField(
                related_name="contributed_in", to="search_database.researchpaper"
            ),
        ),
    ]
