# Generated by Django 6.0.2 on 2026-03-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biosphere", "0003_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="papers",
        ),
    ]
