# Generated by Django 6.0.2 on 2026-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biosphere", "0004_remove_author_papers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
