# Generated by Django 6.0.2 on 2026-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biosphere", "0006_uploadedpapers"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpapers",
            name="paper_state",
            field=models.BooleanField(default=False),
        ),
    ]
