# Generated by Django 6.0.2 on 2026-03-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biosphere", "0007_uploadedpapers_paper_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="Biosphere User", max_length=255),
        ),
    ]
