# Generated by Django 6.0.2 on 2026-03-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biosphere", "0008_user_google_id_user_is_verified_alter_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
